### ISSUE TITLE
Tests Don't Function

### ISSUE THREAD

**Issue by jebediahelliott** [learn-co-curriculum/js-dom-and-events-advanced-selectors-readme#1]
Running the tests results in the following: 
`> jquery-selectors-readme@0.1.0 test /Users/jeb/dev/code/labs/js-dom-and-events-advanced-selectors-readme-v-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 0   -__,------,
 1   -__|  /\_/\ 
 0   -_~|_( x .x) 
     -_ ""  "" 

  0 passing (8ms)
  1 failing

  1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:20:19)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

npm ERR! Test failed.  See above for more details.`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jebediahelliott.

We have updated the materials and believe your issue to have been resolved. In order to access the updated materials, you will need to delete your personal fork of the repo on github and revisit the lesson on learn.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
